Two time series to encode and decode using SFCs.

In [63]:
signal_1 = [5,6,3,4,5]
signal_2 = [1,2,3,2,4]

Demo with Morton encoding using zCurve:

In [64]:
import numpy as np
import zCurve as z

morton = [z.interlace(int(x), int(y), bits_per_dim=10) for x, y in zip(signal_1, signal_2)]
morton_decoded = np.array([z.deinterlace(m, dims=2, total_bits=10) for m in morton])

morton_decoded

array([[5, 1],
       [6, 2],
       [3, 3],
       [4, 2],
       [5, 4]])

Demo with Hilbert encoding from the hilbert library:

In [65]:
import numpy as np
import hilbert as h

hilbert = h.encode(np.ascontiguousarray(np.array([signal_1, signal_2]).T), num_dims=2, num_bits=10)
hilbert_decoded = h.decode(hilbert, num_dims=2, num_bits=10)

hilbert_decoded

array([[5, 1],
       [6, 2],
       [3, 3],
       [4, 2],
       [5, 4]], dtype=uint64)

Hilbert encoding and decoding with hilbertcurve.hilbertcurve.HilbertCurve:

In [66]:
import numpy as np
from hilbertcurve.hilbertcurve import HilbertCurve

h = HilbertCurve(p=10, n=2)
hilbert = [h.distance_from_point([x, y]) for x, y in zip(np.array(signal_1), np.array(signal_2))]
hilbert_decoded = np.array(h.points_from_distances(hilbert))

hilbert_decoded

array([[5, 1],
       [6, 2],
       [3, 3],
       [4, 2],
       [5, 4]])